# Generated by Django 3.2.9 on 2021-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CSS', 'css'), ('HTML', 'html'), ('Javascript', 'javascript'), ('Python', 'python'), ('R', 'r')], default=None, max_length=50, null=True),
        ),
    ]
