# Generated by Django 3.2.9 on 2021-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('python', 'Python'), ('r', 'R')], default=None, max_length=50, null=True),
        ),
    ]
