# Generated by Django 3.2.9 on 2021-11-11 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
